### PR TITLE
Split sregistry into subpackages

### PR DESCRIPTION
**Pull request by tschoonj**
Following discussion in #19, split the sregistry conda package into several subpackages.

### CODE REVIEW

**Comment by vsoch** [comment]
This is fantastic! Could you walk me through how it works?

**Comment by tschoonj** [comment]
Good morning @vsoch 

This is mostly based on the conda [docs](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section) as well as the matplotlib Conda-forge [recipe](https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml).

Basically this modified recipe splits out the plugin dependencies into several appropriately named packages, which contain no installed files, and are exclusively used to handle the dependencies of the the corresponding plugins.

So now if you install `sregistry`, you will only install the dependencies listed in `requirements.txt` as well as `sqlalchemy`, which I made a required dependency (hope that's ok!) since it's required by all plugins.

To install a specific plugin you will need specify it in the `conda install` command which won't do anything except drag in the corresponding requirements.

Hope this is a good solution to your concerns in #19

**Comment by tschoonj** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
@conda-forge-admin, please rerender

**Comment by vsoch** [comment]
This is beautifully done! Should the build number be bumped to 1?

**Comment by vsoch** [comment]
Also note that CircleCI doesn't seem to be building, so the PR from this morning to add the missing dependency can't be merged yet. Once that's done (and we finish here) I'll update the docs to instruct the user how to install from conda in this manner.

**Comment by tschoonj** [comment]
Glad to see you like this approach :smile: 

When the builds go green, this should be ready to be merged in. I had to explicitly disable the Windows build but I don't think that platform makes sense to support anyway.

Build number should always be bumped whenever the recipe is modified but the version is kept the same.

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
okay, let's give it a try! I'll merge here, give a few minutes, and then release on pypi.

**Pull request merged**
