### PR TITLE
Add Swift backend dependencies

### PR DESCRIPTION
**Pull request by tschoonj**
I added the required packages to conda-forge for the openstack CLI, and I thought it would be good to add them here as well...

### CODE REVIEW

**Comment by vsoch** [comment]
Why?

**Review by vsoch — CHANGES_REQUESTED** [review]
This is not how sregistry works - each plugin is considered separate and if a user wants to install it, they do it separately. The package here should not have it.

**Comment by tschoonj** [comment]
Well the recipe already has the AWS, Dropbox, Globus and Google Cloud dependencies, so I thought it would make sense to add the Swift python libraries as well here, to ensure the plugin works out of the box...

Apologies if this was not a smart thing to do...

**Comment by vsoch** [comment]
Gosh I can’t believe I didn’t notice this... these need to be removed right away.

**Comment by tschoonj** [comment]
I thought this was fine to be honest. Conda does not allow a person to specify extra options to drag in additional dependencies, so typically conda packages are built to support as many options as possible.

**Comment by vsoch** [comment]
But the average user won't need all of those libraries. It's really leading down a path to dependency hell, because think of all the other packages this needs to potentially install alongside.

**Comment by tschoonj** [comment]
True, but so far there have been no problems though... and there have been 6.9K downloads so far, which is not bad at all.

**Comment by vsoch** [comment]
I'm fairly upset about this. I wish it was done right in the first place. At this point it would do more damage to remove them. :/

**Comment by tschoonj** [comment]
Apologies... I guess I am responsible for [this](https://github.com/conda-forge/staged-recipes/pull/8441). 😢 

Feel free to remove the plugin dependencies if you think that's the best thing to do.

You are right though that some users would be affected by this since it will probably remove these dependencies from their system since they were not explicitly requested.

**Comment by vsoch** [comment]
hey @conda-forge-admin we need some help here - @tschoonj added every (optional) plugin package to the original recipe (before I was added as a maintainer) and I'm unfortunately just realizing this now. The "right" and clean thing I believe would be to provide only the minimal package, and require the specific user to install additional needed libraries (e.g., for pip this would be `pip install sregistry[aws]` and then not have 10+ other modules that aren't needed, but the issue now is that these are already in the recipe, and I'm not sure if it would do more damage to remove them. I'm also not sure if it's typical in conda to just enforce install of all extra plugins? This seems hugely dangerous for creating some dependency hell when it's not necessary.

I've been troubled by this all day and I can't decide what is best to do, thank you in advance for your help.

**Pull request closed without merging**
